# Use docker-compose to deploy the server container onto docker platform

version: '2'
services:
  istio-analytics:
    build: 
      context: ../
    image: istio-analytics:latest
    container_name: istio-analytics
    networks:
      istio-analytics-mesh:
        aliases:
          - istio-analytics 
    environment:
      - ISTIO_ANALYTICS_TRACE_BACKEND=<trace server name>
      - ISTIO_ANALYTICS_TRACE_SERVER_URL=<trace server url>
      - ISTIO_ANALYTICS_SERVER_PORT=5555
      - ISTIO_ANALYTICS_DEBUG="false"
    expose:
      - "5555"
    ports:
      - "5555:5555"
networks:
  istio-analytics-mesh: {}
