# Use docker-compose to deploy the server container onto docker platform

version: '2'
services:
  istio-analytics:
    build: 
      context: ../
    image: istio-analytics:latest
    container_name: istio-analytics
    networks:
      istio-analytics-mesh:
        aliases:
          - istio-analytics 
    environment:
      - ISTIO_ANALYTICS_TRACE_BACKEND=jaeger
      - ISTIO_ANALYTICS_TRACE_SERVER_URL=http://jaeger:16686
      - ISTIO_ANALYTICS_SERVER_PORT=5555
      - ISTIO_ANALYTICS_DEBUG="false"
    expose:
      - "5555"
    ports:
      - "5555:5555"

  jaeger:
    image:
      jaegertracing/all-in-one:1.7 
    container_name: jaeger
    networks:
      istio-analytics-mesh:
        aliases:
          - jaeger 
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "16686"
      - "9411"
    ports:
      - "16686:16686"
      - "9411:9411"
networks:
  istio-analytics-mesh: {}
