##########################################################################################################
#                                                 Service 0                                                #
##########################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc0
  labels:
    app: svc0
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: svc0
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc0-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc0
        version: v1
    spec:
      containers:
      - name: svc0
        image: iter8/serviceunit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
##########################################################################################################
#                                                 Service 1                                                #
##########################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: svc1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc1-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc1
        version: v1
    spec:
      containers:
      - name: svc1
        image: iter8/serviceunit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
##########################################################################################################
#                                                 Service 2                                                #
##########################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: svc2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc2-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc2
        version: v1
    spec:
      containers:
      - name: svc2
        image: iter8/serviceunit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
##########################################################################################################
#                                                 Service 3                                                #
##########################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc3
  labels:
    app: svc3
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: svc3
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc3-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc3
        version: v1
    spec:
      containers:
      - name: svc3
        image: iter8/serviceunit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
