{
 "title": "cloudtsa demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "entity", "query": "svc0, svc1, svc2, svc3" },
   {
    "name": "detector_type",
    "query": "changedetection, predictivethresholds, peakdetection, thresholdpolicy"
   },
   {
    "name": "metric_name",
    "query": "latency, error_rates, error_counts, load"
   }
  ]
 },
 "panels": [
  {
   "title": "CloudTSA Alerts",
   "type": "graph",
   "gridPos": { "h": 19, "w": 22, "x": 1, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{detector_type=~'$detector_type', metric_name='$metric_name', entity=\"$entity\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "title": "Latency metrics",
   "type": "graph",
   "description": "Average latency for node0",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_request_duration_seconds_sum{destination_service_name='$entity'}[30s])) by (destination_service_name)) / (sum(increase(istio_request_duration_seconds_count{destination_service_name='$entity'}[30s])) by (destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Total Load on Svc3",
   "type": "graph",
   "description": "Graph displaying peaks in the load",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{source_app='istio-ingressgateway', reporter='source', destination_service_name='svc3'}[30s])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Error Count for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{response_code=~'5..', source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[20s])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Error Rate for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_requests_total{response_code=~'5..', source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[30s])) by (destination_service_name)) / (sum(increase(istio_requests_total{source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[30s])) by (destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 0, "y": 53 },
   "content": "<style>\n  .panel-title-container {\n    font-size: x-large;\n  }\n  .graph-legend-series {\n    font-size: 24px;\n  }\n  .grafana-tooltip {\n    font-size: 24px;\n  }\n  div.flot-x-axis > div.flot-tick-label {\n    font-size: medium;\n  }\n  div.flot-y-axis > div.flot-tick-label {\n    font-size: medium;\n  }\n</style>"
  }
 ]
}