'''
Environment variables that control the Istio Analytics server
'''

ISTIO_ANALYTICS_SERVER_PORT_ENV = 'ISTIO_ANALYTICS_SERVER_PORT'
ISTIO_ANALYTICS_DEBUG_ENV = 'ISTIO_ANALYTICS_DEBUG'
ISTIO_ANALYTICS_ZIPKIN_HOST_ENV = 'ISTIO_ANALYTICS_ZIPKIN_HOST'
