'''
Environment variables that control the Istio Analytics server
'''

ISTIO_ANALYTICS_SERVER_PORT_ENV = 'ISTIO_ANALYTICS_SERVER_PORT'
ISTIO_ANALYTICS_DEBUG_ENV = 'ISTIO_ANALYTICS_DEBUG'

ISTIO_ANALYTICS_TRACE_BACKEND_ENV = 'ISTIO_ANALYTICS_TRACE_BACKEND'
ISTIO_ANALYTICS_TRACE_SERVER_URL_ENV = 'ISTIO_ANALYTICS_TRACE_SERVER_URL'
ISTIO_ANALYTICS_TRACE_SERVER_OVERRIDE_ENV = 'ISTIO_ANALYTICS_TRACE_SERVER_OVERRIDE'

ISTIO_ANALYTICS_SKYDIVE_HOST_ENV = 'ISTIO_ANALYTICS_SKYDIVE_HOST'
ISTIO_ANALYTICS_SKYDIVE_HOST_DEFAULT = 'http://9.4.193.143:30703'
ISTIO_ANALYTICS_SKYDIVE_OVERRIDE_ENV = 'ISTIO_ANALYTICS_SKYDIVE_OVERRIDE'
