'''
Environment variables that control the Istio Analytics server
'''

ISTIO_ANALYTICS_SERVER_PORT_ENV = 'ISTIO_ANALYTICS_SERVER_PORT'
ISTIO_ANALYTICS_DEBUG_ENV = 'ISTIO_ANALYTICS_DEBUG'
ISTIO_ANALYTICS_ZIPKIN_HOST_ENV = 'ISTIO_ANALYTICS_ZIPKIN_HOST'
ISTIO_ANALYTICS_ZIPKIN_OVERRIDE_ENV = 'ISTIO_ANALYTICS_ZIPKIN_OVERRIDE'

# The Skydive host should be a URL for example http://9.4.193.143:30703/topology
# See https://github.com/skydive-project/skydive
ISTIO_ANALYTICS_SKYDIVE_HOST_ENV = 'ISTIO_ANALYTICS_SKYDIVE_HOST'
ISTIO_ANALYTICS_SKYDIVE_HOST_DEFAULT = 'http://9.4.193.143:30703'
