# Use docker-compose to deploy the server container onto docker platform

version: '2'
services:
  istio-analytics:
    build: 
      context: ../
    image: istio-analytics:latest
    container_name: istio-analytics
    networks:
      istio-analytics-mesh:
        aliases:
          - istio-analytics 
    environment:
      - ISTIO_ANALYTICS_ZIPKIN_HOST=http://zipkin:9411
      - ISTIO_ANALYTICS_SERVER_PORT=5555
      - ISTIO_ANALYTICS_DEBUG="false"
    expose:
      - "5555"
    ports:
      - "5555:5555"

  zipkin:
    image:
      openzipkin/zipkin
    container_name: zipkin
    networks:
      istio-analytics-mesh:
        aliases:
          - zipkin 
    expose:
      - "9411"
    ports:
      - "9411:9411"
networks:
  istio-analytics-mesh: {}
