#!/bin/bash
docker rm -f istio_analytics

CONTAINER_PORT_EXPOSED=5555
HOST_PORT_EXPOSED=5555
ISTIO_ANALYTICS_ZIPKIN_HOST="http://localhost:9411"
ISTIO_ANALYTICS_SERVER_PORT="5555"
ISTIO_ANALYTICS_DEBUG="false"

docker run --name istio_analytics -d --expose $CONTAINER_PORT_EXPOSED -p 5555:$CONTAINER_PORT_EXPOSED -e ISTIO_ANALYTICS_ZIPKIN_HOST=$ISTIO_ANALYTICS_ZIPKIN_HOST -e ISTIO_ANALYTICS_SERVER_PORT=$ISTIO_ANALYTICS_SERVER_PORT -e ISTIO_ANALYTICS_DEBUG=$ISTIO_ANALYTICS_DEBUG istio_analytics
