#!/bin/bash

docker rm -f istio-analytics

CONTAINER_PORT_EXPOSED=5555
HOST_PORT_EXPOSED=5555
ISTIO_ANALYTICS_SERVER_PORT="5555"
ISTIO_ANALYTICS_DEBUG="false"

if [ -z ${ISTIO_ANALYTICS_ZIPKIN_HOST} ]; then
  ISTIO_ANALYTICS_ZIPKIN_HOST="http://localhost:9411"
  echo "ISTIO_ANALYTICS_ZIPKIN_HOST not set. Defauting to $ISTIO_ANALYTICS_ZIPKIN_HOST"
fi

docker run --name istio-analytics -d --expose $CONTAINER_PORT_EXPOSED -p 5555:$CONTAINER_PORT_EXPOSED -e ISTIO_ANALYTICS_ZIPKIN_HOST=$ISTIO_ANALYTICS_ZIPKIN_HOST -e ISTIO_ANALYTICS_SERVER_PORT=$ISTIO_ANALYTICS_SERVER_PORT -e ISTIO_ANALYTICS_DEBUG=$ISTIO_ANALYTICS_DEBUG istio-analytics
