{
 "title": "cloudtsa demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency for Svc0",
   "type": "graph",
   "description": "Average latency for node0",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_request_duration_seconds_sum{destination_service_name='svc0'}[30s])) by (destination_service_name)) / (sum(increase(istio_request_duration_seconds_count{destination_service_name='svc0'}[30s])) by (destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "CloudTSA (latency) Alerts for Svc0",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc0\", metric_name=\"latency\",source=\"ingress-gateway\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "title": "Latency for Svc1",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_request_duration_seconds_sum{destination_service_name='svc1'}[30s])) by (destination_service_name)) / (sum(increase(istio_request_duration_seconds_count{destination_service_name='svc1'}[30s])) by (destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "CloudTSA (latency) Alerts for Svc1",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc1\",detector_type=\"changedetection\",metric_name=\"latency\",source=\"ingress-gateway\"} ",
     "legendFormat": "{{detector_type}}"
    },
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc1\", detector_type=\"thresholdpolicy\", metric_name=\"latency\", source=\"ingress-gateway\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "title": "Error Count for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{response_code=~'5..', source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[20s])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "CloudTSA (Errorcount) Alerts for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc2\", metric_name=\"error_counts\", source=\"ingress-gateway\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "title": "Error Rate for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_requests_total{response_code=~'5..', source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[30s])) by (destination_service_name)) / (sum(increase(istio_requests_total{source_app='istio-ingressgateway', reporter='source', destination_service_name='svc2', source_app='istio-ingressgateway'}[30s])) by (destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "CloudTSA (Error Rate) Alerts for Svc2",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc2\", metric_name=\"error_rates\", source=\"ingress-gateway\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "title": "Total Load on Svc3",
   "type": "graph",
   "description": "Graph displaying peaks in the load",
   "gridPos": { "h": 17, "w": 11, "x": 1, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{source_app='istio-ingressgateway', reporter='source', destination_service_name='svc3'}[30s])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "CloudTSA (Load) Alerts for Svc3",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudtsa_alarm_count_total{destination=\"svc3\",detector_type=\"peakdetection\"}",
     "legendFormat": "{{detector_type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 0, "y": 85 },
   "content": "<style>\n  .panel-title-container {\n    font-size: x-large;\n  }\n  .graph-legend-series {\n    font-size: 24px;\n  }\n  .grafana-tooltip {\n    font-size: 24px;\n  }\n  div.flot-x-axis > div.flot-tick-label {\n    font-size: medium;\n  }\n  div.flot-y-axis > div.flot-tick-label {\n    font-size: medium;\n  }\n</style>"
  }
 ]
}