apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.traceServer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.traceServer.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.traceServer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.traceServer.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.traceServer.name }}
          image: "{{ .Values.traceServer.image.repository }}:{{ .Values.traceServer.image.tag }}"
          imagePullPolicy: {{ .Values.traceServer.image.pullPolicy }}
          ports:
            {{- range $key, $val := .Values.traceServer.image.expose }}
            - containerPort: {{ $val }}
            {{- end }}
          {{- if .Values.traceServer.image.zipkinCollector.enabled }}
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "{{ .Values.traceServer.image.zipkinCollector.port }}"
          {{- end }}
