apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.server.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    {{- range $key, $val := .Values.server.service.ports }}
    - {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ .Values.server.name }}
